[package]
name = "teloxide"
version = "0.3.1"
edition = "2018"
description = "An elegant Telegram bots framework for Rust"
repository = "https://github.com/teloxide/teloxide"
documentation = "https://docs.rs/teloxide/"
readme = "README.md"
keywords = ["teloxide", "telegram", "telegram-bot", "telegram-bot-api"]
license = "MIT"
exclude = ["media"]
authors = [
        "Temirkhan Myrzamadi <hirrolot@gmail.com>",
        "Waffle Lapkin <waffle.lapkin@gmail.com>",
        "p0lunin <dmytro.polunin@gmail.com>",
        "Mishko torop'izhko",
        "Mr-Andersen",
        "Sergey Levitin <selevit@gmail.com>",
        "Rustem B. <bakirov.com@yandex.ru>",
        "Alexey Fedechkin <aleksey-fedechkin@rambler.ru>"
]

[badges]
maintenance = { status = "actively-developed" }

[features]
redis-storage = ["redis"]
cbor-serializer = ["serde_cbor"]
bincode-serializer = ["bincode"]

frunk- = ["frunk"]

macros = ["teloxide-macros"]

nightly = [] # currently used only for `README.md` tests

[dependencies]
serde_json = "1.0.55"
serde = { version = "1.0.114", features = ["derive"] }

tokio = { version = "0.2.21", features = ["fs", "stream"] }
tokio-util = "0.3.1"

reqwest = { version = "0.10.6", features = ["json", "stream"] }
log = "0.4.8"
lockfree = "0.5.1"
bytes = "0.5.5"
mime = "0.3.16"

derive_more = "0.99.9"
thiserror = "1.0.20"
async-trait = "0.1.36"
futures = "0.3.5"
pin-project = "0.4.22"
serde_with_macros = "1.1.0"

redis = { version = "0.16.0", optional = true }
serde_cbor = { version = "0.11.1", optional = true }
bincode = { version = "1.3.1", optional = true }
frunk = { version = "0.3.1", optional = true }

teloxide-macros = "0.3.2"

[dev-dependencies]
smart-default = "0.6.0"
rand = "0.7.3"
pretty_env_logger = "0.4.0"
lazy_static = "1.4.0"
tokio = { version = "0.2.21", features = ["fs", "stream", "rt-threaded", "macros"] }

[package.metadata."docs.rs"]
all-features = true

[[test]]
name = "redis"
path = "tests/redis.rs"
required-features = ["redis-storage", "cbor-serializer", "bincode-serializer"]
